# Form implementation generated from reading ui file 'Translet.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 416)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Фото/depositphotos_420527924-stock-illustration-vector-language-translator-editable-icon.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_with_lag = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_with_lag.setGeometry(QtCore.QRect(10, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_with_lag.setFont(font)
        self.comboBox_with_lag.setObjectName("comboBox_with_lag")
        self.comboBox_in_lag = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_in_lag.setGeometry(QtCore.QRect(440, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_in_lag.setFont(font)
        self.comboBox_in_lag.setObjectName("comboBox_in_lag")
        self.textEdit_translet_with = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_translet_with.setEnabled(True)
        self.textEdit_translet_with.setGeometry(QtCore.QRect(10, 50, 291, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_translet_with.setFont(font)
        self.textEdit_translet_with.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textEdit_translet_with.setObjectName("textEdit_translet_with")
        self.textEdit_translet_in = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_translet_in.setGeometry(QtCore.QRect(440, 50, 291, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_translet_in.setFont(font)
        self.textEdit_translet_in.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textEdit_translet_in.setReadOnly(True)
        self.textEdit_translet_in.setPlaceholderText("")
        self.textEdit_translet_in.setObjectName("textEdit_translet_in")
        self.pushButton_translet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_translet.setEnabled(True)
        self.pushButton_translet.setGeometry(QtCore.QRect(580, 340, 151, 31))
        self.pushButton_translet.setObjectName("pushButton_translet")
        self.pushButton_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Clear.setGeometry(QtCore.QRect(10, 340, 151, 31))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_perer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_perer.setGeometry(QtCore.QRect(340, 10, 71, 31))
        self.pushButton_perer.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Фото/free-icon-two-arrows-pointing-right-and-left-46246.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_perer.setIcon(icon1)
        self.pushButton_perer.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_perer.setObjectName("pushButton_perer")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(580, 380, 151, 31))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_copy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copy.setGeometry(QtCore.QRect(10, 380, 151, 31))
        self.pushButton_copy.setObjectName("pushButton_copy")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_Clear.clicked.connect(self.textEdit_translet_with.clear) # type: ignore
        self.pushButton_Clear.clicked.connect(self.textEdit_translet_in.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Переводчик"))
        self.textEdit_translet_with.setPlaceholderText(_translate("MainWindow", "Введите ваш текст"))
        self.pushButton_translet.setText(_translate("MainWindow", "Перевести"))
        self.pushButton_Clear.setText(_translate("MainWindow", "Очистить поля"))
        self.pushButton_exit.setText(_translate("MainWindow", "Выйти"))
        self.pushButton_copy.setText(_translate("MainWindow", "Копировать перевод"))
